---
- name: Ensure composer directory exists
  ansible.builtin.file:
    group: "{{ item.user }}"
    mode: 0755
    owner: "{{ item.user }}"
    path: "{{ item.home }}"
    state: directory
  loop: "{{ composer_users }}"

- name: Ensure composer auth.json exists
  ansible.builtin.template:
    dest: "{{ item.home }}/auth.json"
    group: "{{ item.user }}"
    mode: 0640
    owner: "{{ item.user }}"
    src: auth.json.j2
  loop: "{{ composer_users }}"
