---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-composer
      composer_users:
        - user: root
          home: /root/.composer
          auth:
            http-basic:
              github.com:
                username: alice
                password: foo
